config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  post '/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#post_with_reactions', as: 'my_reactions'

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :author, length: { maximum: 20 }
  validates :content, presence: true, length: { minimum: 2, maximum: 300 }

  before_validation :set_default_author, on: :create

  private

  def set_default_author
    self.author = user.present? ? user.email : 'anónimo'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy
  has_many :users, through: :reactions
  has_many :comments, dependent: :destroy

  def count_with_reaction_type(arg)
    number = reactions.where(reaction_type: arg).count
    "#{number} #{arg}s"
  end

  def find_reaction_type_user_relation(user)
    reactions.find_by(user_id: user.id).reaction_type
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :reaction_type, acceptance: {
    accept: %w[like dislike]
  }

  def self.reaction_type
    %w[like dislike]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :set_default_role

  has_many :posts
  has_many :reactions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def admin?
    role == 'admin'
  end

  private

  def set_default_role
    self.role ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_comment, only: %i[show edit update destroy create new]
  before_action :authenticate_user!, except: %i[show create]
  before_action :authorize_comment_edit, only: %i[edit update destroy]

  def new
    return unless user_signed_in?

    @comment = @post.comments.build
  end

  def show
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user if user_signed_in?
    @comment.user ||= User.find_by(email: 'whatshername@senkutech.cl') # Buscar usuario genérico si no hay usuario conectado
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to @post, alert: 'Failed to create comment.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.admin? || current_user == @comment.user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: 'Comment was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      redirect_to @post, alert: 'You are not authorized to delete this comment.'
    end
  end

  private

  def set_post_comment
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id]) if params[:id]
  end

  def comment_params
    params.require(:comment).permit(:author, :content)
  end

  def authorize_comment_edit
    return if current_user.admin? || (@comment && @comment.user == current_user)

    redirect_to root_path, alert: 'You are not authorized to perform this action.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if current_user.admin? || current_user == @post.user
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @post, alert: 'You are not authorized to perform this action.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!

  def user_reaction
    @user = current_user
    @post = Post.find(params[:post_id])
    reaction = Reaction.find_by(user_id: @user.id, post_id: @post.id)
    return flash.now[:alert] = 'You already reacted to this post' if reaction

    @new_reaction = Reaction.new(user_id: @user.id, post_id: @post.id, reaction_type: params[:reaction_type])
    respond_to do |format|
      if @new_reaction.save!
        format.html do
          redirect_to post_path(@post),
                      notice: "#{current_user.email} has stated that it #{@new_reaction.reaction_type} the post"
        end
      else
        format.html { redirect_to post_path(@post), status: :unprocessable_entity }
      end
    end
  end

  def post_with_reactions
    @reactions = current_user.reactions
    post_ids = @reactions.map(&:post_id)
    @post = Post.where(id: post_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="fs-6">
    <%= comment.content %>
  </p>
  <p class="fs-6 fst-italic text-end mt-5">
    By: 
    <%= comment.author %>
  </p>
</div>

app/views/comments/_form.html.erb
<!-- Form for create new comments -->
<%= form_for([@post, Comment.new]) do |f| %>
  <div class="d-flex flex-column">
    <div class="field">
      <%= f.label :content, class: "d-block mb-2 fs-5" %>
      <%= f.text_area :content, minlength: 2, maxlength: 300, class:"w-100 p-2 rounded-2 bg-custom-comments", rows: 5 %>
    </div>
    <div class="actions">
      <%= f.submit 'Create Comment', class: "btn btn-sm btn-outline-success my-2" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h3 class="display-5">Edit Comment</h3>
<div class="border border-secondary mt-4 rounded-4 p-3">
  <%= form_for([@post, @comment]) do |f| %>
    <div class="field">
      <%= f.label :content, class: "d-block mb-2 fs-5" %>
      <%= f.text_area :content, class:"w-100 p-2 rounded-2", rows: 5 %>
    </div>
    <div class="mt-3 d-flex align-items-center gap-5">
      <%= f.submit 'Update Comment', class: "btn btn-outline-warning" %>
      <%= link_to 'Delete Comment', post_comment_path(@post, @comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-warning" %>
      <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
    </div>
  <% end %>
</div>

app/views/comments/show.html.erb
<div class="border border-secondary rounded-4 p-3">
  <%= render @comment %>
  <% if user_signed_in? && (@comment.user == current_user || current_user.admin?) %>
    <div class="d-flex gap-4 align-items-center justify-content-center">
      <%= link_to "Back", edit_post_comment_path(@comment.post, @comment), class: "btn btn-outline-secondary" %>
      <%= button_to "Delete", post_comment_path(@comment.post, @comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="Erick A. Jaime Jara">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body class="bg-custom-body container" data-bs-theme="primary">
    <%= render 'shared/navbar' %>
    <main class="mt-5 pt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </main>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fe972eba09.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="d-flex flex-column">
    <div>
      <%= form.label :title, class: "d-block mb-2" %>
      <%= form.text_field :title, class:"w-100 p-2 rounded-2 border border-secondary" %>
    </div>
    <div class="my-3">
      <%= form.label :content, class: "d-block mb-2" %>
      <%= form.text_area :content, class:"w-100 p-2 rounded-2", rows: 10, cols: 30 %>
    </div>
    <div class="mb-3">
      <%= form.submit "Confirm Changes", class: "btn btn-sm btn-outline-success" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="fs-4 fw-bold">
    <%= post.title %>
  </p>
  <p class="fs-6">
    <%= simple_format(post.content) %>
  </p>
  <p class="fs-6 fst-italic text-end mt-5">
    By: 
    <%= post.user.email %>
  </p>
</div>

app/views/posts/edit.html.erb
<h3 class="display-6">Editing: <%= @post.title %></h3>
<div class="border border-secondary mt-4 rounded-4 p-3">
  <%= render "form", post: @post %>
  <div class="d-flex gap-4">
    <%= link_to "Show this post", @post, class:"btn btn-outline-primary" %> |
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="d-flex align-items-center justify-content-between mb-3 b">
  <h1 class="display-5 text-custom-title">Posts</h1>
  <% if user_signed_in? %>
    <%= link_to "New post", new_post_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="mb-5 border border-3s border-dark-subtle p-3 rounded-4">
      <%= render post %>
      <p>
        <%= link_to "Show this post", post, class: "btn btn-outline-secondary" %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render "form", post: @post %>
<div class="mt-3">
  <%= link_to "Back to posts", posts_path, class: "btn btn-outline-secondary" %>
</div>

app/views/posts/show.html.erb
<div class="p-3 border border-secondary rounded-4">
  <%= render @post %>
  <div id="reactions-wraper" class="">
    <div class="mt-2 d-flex gap-3">
      <p>
        <%= @post.count_with_reaction_type('like') %>
        <i class="fa-regular fa-thumbs-up" style="color: #164258;"></i>
      </p>
      <p>
        <%= @post.count_with_reaction_type('dislike') %>
        <i class="fa-regular fa-thumbs-down" style="color: #164258;"></i>
      </p>
    </div>
    <% if user_signed_in? %>
      <div class="d-flex gap-4">
        <% Reaction.reaction_type.each do |reaction_type| %>
          <%= button_to "#{reaction_type}", user_reaction_path(post_id: @post.id, reaction_type: reaction_type), method: :post, class: "btn btn-sm btn-outline-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="d-flex gap-4 align-items-center mt-5 justify-content-center">
    <%= link_to "Back to posts", posts_path, class:"btn btn-sm btn-outline-secondary m-0" %>
    <% if current_user && (current_user.admin? || current_user == @post.user) %>
      <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-sm btn-outline-warning m-0" %>
      <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-sm btn-outline-danger mt-2" %>
    <% end %>
  </div>
</div>
<div id="comments-section">
  <h4 class="display-6 my-3">Comments</h4>
  <% @comments.each do |comment| %>
    <div class="border border-secondary rounded-4 p-3 my-2">
      <p class="fst-italic fs-5">
        <%= comment.author == "whatshername@senkutech.cl" ? "Anonimo" : comment.author %>:
      </p>
      <p class="fs-6"><%= simple_format(comment.content) %></p>
      <% if current_user && (current_user.admin? || current_user.email == comment.author) %>
        <%= link_to 'Edit', edit_post_comment_path(@post, comment), class:"btn btn-sm btn-outline-warning" %>
      <% end %>
    </div>
  <% end %>
  <%= render 'comments/form' %>
</div>

app/views/reactions/_counters.html.erb
<div class="container">
  <ul>
    <% Reaction.reaction_type.each do |reaction_type| %>
      <li> <%= @post.count_with_reaction_type(reaction_type) %>
      <% end %>
    </ul>
  </div>

app/views/reactions/post_with_reactions.erb
<h1>Post</h1>
<ul>
  <% @post.each do |post| %>
    <li>
      <%= post.title %> -
      <%= post.find_reaction_type_user_relation(current_user) %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    </li>
  <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top bg-custom-nav" data-bs-theme="dark">
  <div class="container-fluid">
     
    <%= link_to root_path, class: "navbar-brand" do %>
      <h4 class="m-0">
        <%= image_tag("svg.png", alt:"Crazy4Cats", class: "imglogo") %>
        Crazy4Cats
      </h4>
    <% end %>

    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light me-3" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Opciones</a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
            <% end %>
            <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Tus reacciones', my_reactions_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>